name: Build OnePlus Ace 5 Kernelsu

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  workflow_dispatch:
   
jobs:
  Build-OnePlus-Ace-5-Kernelsu-VFS-With-BBR3:
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 4096
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Get build space
        run: |
          free -h
          df -h
          
      - name: Set CONFIG Environment Variable
        run: |
          # Set CONFIG dynamically based on matrix values
          CONFIG="opace5"
          
          # Set CONFIG as an environment variable for future steps
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          
          echo "CONFIG set to: $CONFIG"
      
      - name: Install Repo
        run: |
          # Install dependencies
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV
      
      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."
    
          # Define the branch names using the matrix values
          SUSFS_BRANCH="gki-android14-6.1"

          # Debug print the branches
          echo "Using branch for SUSFS: $SUSFS_BRANCH"

          # Clone repositories using the branch names
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
          git clone https://github.com/TheWildJames/kernel_patches.git
          git clone https://github.com/google/bbr.git -b v3
        
      - name: Initialize and Sync Kernel Source
        run: |
          echo "Creating folder for configuration: $CONFIG..."
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          
          # Initialize and sync kernel source
          echo "Initializing and syncing kernel source..."
          $REPO init -u https://github.com/MClengchuan/oneplus_kernel_manifest.git -b refs/heads/oneplus/sm8650 -m oneplus_ace5_v.xml --repo-rev=v2.16 --depth=1
          
          # Sync repo and apply patches
          $REPO --version
          $REPO --trace sync -c -j$(nproc --all) --no-tags --fail-fast      
      
      - name: Add BBRV3
        run: |
          echo "Add BBRV3"
          cd "$CONFIG/kernel_platform"
          cp /home/runner/work/O11/O11/bbr/net/ipv4/tcp_bbr.c ./common/net/ipv4/
      
      - name: Add KernelSU-Next
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG/kernel_platform"
          echo "Adding KernelSU..."
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          cd ./KernelSU-Next/kernel
          ls -la /home/runner/work/O11/O11/opace5/kernel_platform/KernelSU-Next/
          
          GIT_COMMIT_COUNT=$(/usr/bin/git rev-list --count HEAD)
          echo "Git commit count: $GIT_COMMIT_COUNT"
          
          KSU_VERSION=$(expr $GIT_COMMIT_COUNT + 10198)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" ./Makefile
          
      - name: Apply SUSFS Patches
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG/kernel_platform"
          
          echo "Applying SUSFS patches..."
          
          # Copy SUSFS patches
          cp /home/runner/work/O11/O11/susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
          cp /home/runner/work/O11/O11/susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp /home/runner/work/O11/O11/susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cd ./KernelSU-Next
          
          # Change to common directory and apply SUSFS patch
          cd ../common
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
          
      - name: Apply Next-SUSFS Patches
        run: |
          cd /home/runner/work/O11/O11/opace5/kernel_platform/
          cd ./KernelSU-Next
          echo "Applying next SUSFS patches..."
          cp /home/runner/work/O11/O11/kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./
          patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
          
          cd /home/runner/work/O11/O11/opace5/kernel_platform/common
          cp /home/runner/work/O11/O11/kernel_patches/next/syscall_hooks.patch ./
          patch -p1 -F 3 < syscall_hooks.patch
      
      - name: Apply Hide Stuff Patches
        run: |
          cd /home/runner/work/O11/O11/opace5/kernel_platform/common
          cp /home/runner/work/O11/O11/kernel_patches/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch || true
      
      - name: Add SUSFS Configuration Settings
        run: |
          cd "$CONFIG/kernel_platform"
          
          echo "Adding configuration settings to gki_defconfig..."
          
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_WITH_KPROBES=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig 
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_DEFAULT_TCP_CONG=\"bbr\"" >> ./common/arch/arm64/configs/gki_defconfig
      
      - name: Run sed and perl Commands
        run: |
          cd "$CONFIG/kernel_platform"
          echo "Running sed commands..."
          sed -i 's/check_defconfig//' ./common/build.config.gki
          sed -i '$s|echo "\$res"|echo "\$res-VFS"|' ./common/scripts/setlocalversion
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
      
      - name: Build the Kernel
        run: |
          cd "$CONFIG"
          echo "Building the kernel..."
          rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
          ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki
      
      - name: Create Bootimgs Folder and Copy Images
        run: |
          cd "$CONFIG"
          cp ./out/dist/Image ../AnyKernel3/Image
          
      - name: Create ZIP Files for Different Formats
        run: |
          cd ./AnyKernel3
          ZIP_NAME="AnyKernel3_KernelSU_Next_VFS_${KSUVER}_oneplus_ace5.zip"
          zip -r "../$ZIP_NAME" ./*
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.CONFIG }}
          path: |
            *.zip
