name: OrangeFox - Build

# Credits to:
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru for Recovery Builder Template
# And all Contributors in every repositories I used

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
          - 12.1
          - 11.0
      DEVICE_TREE:
        description: 'OrangeFox Device Tree'
        required: true
        default: 'https://github.com/SakuraKyuo/device_oneplus_giulia-TWRP'
      DEVICE_TREE_BRANCH:
        description: 'OrangeFox Device Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/oneplus/giulia'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'giulia'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - boot
          - recovery
          - vendorboot

jobs:
  build:
    name: Build OrangeFox Recovery by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Checkout the workflow repository
      - name: Checkout
        uses: actions/checkout@v4

      # Clean up the runner to free disk space
      - name: Clean-up
        uses: rokibhasansagar/slimhub_actions@main

      # Set up swap space to prevent memory issues during compilation
      - name: Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      # Install build dependencies and set up the environment
      - name: Build Environment
        run: |
          sudo apt update
          sudo apt install aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
          cd scripts
          sudo bash setup/android_build_env.sh

      # Initialize the OrangeFox manifest
      - name: Set-up Manifest
        if: inputs.MANIFEST_BRANCH == '11.0' || inputs.MANIFEST_BRANCH == '12.1'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
          cd ${GITHUB_WORKSPACE}/OrangeFox
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git clone https://gitlab.com/OrangeFox/sync.git -b master
          cd sync
          ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

      # Clone the device tree
      - name: Clone Device Tree
        run: |
          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
          git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
          cd ${{ inputs.DEVICE_PATH }}
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # Patch all .mk files to add TW_MAX_BRIGHTNESS, prioritizing twrp_giulia.mk
      - name: Patch Device Tree for TW_MAX_BRIGHTNESS
        run: |
          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/${{ inputs.DEVICE_PATH }}
          echo "Listing all files in device tree directory (${{ inputs.DEVICE_PATH }}):"
          ls -la
          echo "Searching for .mk files..."
          patched=false
          # Prioritize twrp_giulia.mk if it exists
          if [ -f twrp_giulia.mk ]; then
            echo "Checking twrp_giulia.mk for TW_MAX_BRIGHTNESS"
            if ! grep -q "TW_MAX_BRIGHTNESS" twrp_giulia.mk; then
              echo "TW_MAX_BRIGHTNESS := 255" >> twrp_giulia.mk
              echo "Added TW_MAX_BRIGHTNESS := 255 to twrp_giulia.mk"
              patched=true
            else
              echo "TW_MAX_BRIGHTNESS already defined in twrp_giulia.mk"
              patched=true
            fi
          fi
          # Check other .mk files if twrp_giulia.mk was not patched
          if [ "$patched" = false ]; then
            for mk_file in $(find . -maxdepth 1 -type f -name "*.mk" ! -name "twrp_giulia.mk"); do
              mk_file=$(basename "$mk_file")
              echo "Checking $mk_file for TW_MAX_BRIGHTNESS"
              if ! grep -q "TW_MAX_BRIGHTNESS" "$mk_file"; then
                echo "TW_MAX_BRIGHTNESS := 255" >> "$mk_file"
                echo "Added TW_MAX_BRIGHTNESS := 255 to $mk_file"
                patched=true
              else
                echo "TW_MAX_BRIGHTNESS already defined in $mk_file"
              fi
            done
          fi
          # If no .mk files were found, create orangefox.mk as a fallback
          if [ ! -n "$(find . -maxdepth 1 -type f -name '*.mk')" ]; then
            echo "No .mk files found in ${{ inputs.DEVICE_PATH }}. Creating orangefox.mk"
            echo "# OrangeFox Recovery configuration" > orangefox.mk
            echo "TW_MAX_BRIGHTNESS := 255" >> orangefox.mk
            patched=true
          fi
          # Fail if no patching was done and no .mk files exist
          if [ "$patched" = false ] && [ -n "$(find . -maxdepth 1 -type f -name '*.mk')" ]; then
            echo "Warning: TW_MAX_BRIGHTNESS was already defined in all .mk files"
          elif [ "$patched" = false ]; then
            echo "Error: No .mk files found and unable to create orangefox.mk"
            exit 1
          fi

      # Build OrangeFox Recovery
      - name: Building OrangeFox
        run: |
          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_${{ inputs.DEVICE_NAME }}-eng
          make clean
          mka adbd ${{ inputs.BUILD_TARGET }}image

      # Set release properties (e.g., build date)
      - name: Set Release Properties
        run: |
          echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
          cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

      # Upload the build artifacts to GitHub Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
            OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
          name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
          tag_name: ${{ github.run_id }}
          body: |
            ## OrangeFox Recovery Build - Unofficial
            Build: fox_${{ inputs.MANIFEST_BRANCH }}
            Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
            Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
